# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abaryshe <abaryshe@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/11/24 16:24:28 by abaryshe          #+#    #+#              #
#    Updated: 2024/11/25 13:57:14 by abaryshe         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libftprintf.a
CC = cc
CMPFLAGS = -Wall -Wextra -Werror
SOURCE = ft_printf.c
OBJECT = ${SOURCE:.c=.o}
FORCE_REMOVE = rm -f

all: ${NAME}

${NAME}: 
    
clean:

fclean:

re:
